Repository ISISComputingGroup/EPICS-lakeshore340, pull requests merged in 2021-02, with the labels that each got.

#2 Add excitation features to lakeshore 340
  Lakeshore340Sup/Lakeshore340.db
  Lakeshore340Sup/Lakeshore340.dbd
  Lakeshore340Sup/Lakeshore340.proto
  Lakeshore340Sup/Makefile
  Lakeshore340Sup/lakeshore340excitations.c
  Lakeshore340Sup/lakeshore340excitations.h
  Lakeshore340Sup/lakeshore340excitationsTests.cpp
  configure/Makefile
  configure/RELEASE
  excitation_thresholds/InvalidLines.txt
  excitation_thresholds/Test1.txt
Labels: size/XL

#3 Process records to ensure they update in the OPI
  Lakeshore340Sup/Lakeshore340.db
Labels: size/XS

#4 Fixes for vs2010 and other minor things
  Lakeshore340Sup/lakeshore340excitations.c
  Lakeshore340Sup/lakeshore340excitations.h
Labels: size/M

#5 Use enum16 data type
  Lakeshore340Sup/Lakeshore340.db
  Lakeshore340Sup/lakeshore340excitations.c
Labels: size/XS
